"use strict";

/*
 * Речник фраза и идиома, без интернета и без AI.
 *
 * dir:  "sr" — израз се тражи у српском тексту, "no" — у норвешком.
 * re:   образац над „нормализованим“ текстом: српски у латиници, мала слова,
 *       без квачица (č ć → c, š → s, ž → z, đ → dj); норвешки само мала слова.
 * literal: дословно на други језик; equivalent: прави еквивалент или, ако га нема
 *       (has: false), најприроднији опис. level: CEFR ниво израза.
 */
const IDIOMS = [
  // ---------------- српски → норвешки ----------------
  { dir: "sr", re: /sekira u med/, original: "пала ми је секира у мед", literal: "øksa har falt i honningen for meg", equivalent: "å ha flaks", has: true, level: "A2",
    explanation: "Кад некоме изненада крене набоље. Норвежани кажу једноставно „jeg hadde flaks“ (имао сам среће) или „for en flaks!“." },
  { dir: "sr", re: /\bnije (mi|ti|mu|joj|nam|vam|im) do\b/, original: "није ми до тога", literal: "det er ikke til meg til det", equivalent: "jeg er ikke i humør til det / jeg orker ikke", has: false, level: "B1",
    explanation: "Норвешки нема исти израз. Кад немаш расположења: „jeg er ikke i humør til det“, кад немаш снаге: „jeg orker ikke“ („orke“ је врло честа реч)." },
  { dir: "sr", re: /na zivce/, original: "ићи (некоме) на живце", literal: "å gå noen på nervene", equivalent: "å gå noen på nervene", has: true, level: "A2",
    explanation: "Исти израз постоји и у норвешком: „Han går meg på nervene.“" },
  { dir: "sr", re: /ni luk jeo/, original: "ни лук јео ни лук мирисао", literal: "verken spist løk eller luktet løk", equivalent: "å late som ingenting", has: true, level: "B2",
    explanation: "Кад се неко прави невешт. „Han lot som ingenting“ — правио се као да ништа није било." },
  { dir: "sr", re: /grom iz vedr/, original: "као гром из ведра неба", literal: "som torden fra klar himmel", equivalent: "som lyn fra klar himmel", has: true, level: "B1",
    explanation: "Скоро исто, само је у норвешком муња (lyn), а не гром." },
  { dir: "sr", re: /zec lez|je (taj )?zec\b/, original: "ту је зец", literal: "der ligger haren", equivalent: "det er der skoen trykker", has: true, level: "B2",
    explanation: "Кад откријеш прави проблем. Норвешки: „ту жуља ципела“." },
  { dir: "sr", re: /(pare|para|novac|novca|novce) kroz prozor/, original: "бацати паре кроз прозор", literal: "å kaste penger gjennom vinduet", equivalent: "å kaste penger ut av vinduet", has: true, level: "B1",
    explanation: "Исти израз: трошити новац узалуд." },
  { dir: "sr", re: /na vrbi rodi/, original: "кад на врби роди грожђе", literal: "når det vokser druer på pilen", equivalent: "når det blir to torsdager i en uke", has: true, level: "B2",
    explanation: "За нешто што се никад неће десити. Норвешки: „кад у недељи буду два четвртка“." },
  { dir: "sr", re: /palceve/, original: "држати палчеве", literal: "å holde tomlene", equivalent: "å holde tommelen for noen", has: true, level: "A2",
    explanation: "„Jeg holder tommelen for deg!“ У норвешком се држи један палац (tommelen), а не оба." },
  { dir: "sr", re: /(lupa|razbija)\w* (sebi )?glavu/, original: "лупати (разбијати) главу", literal: "å slå hodet", equivalent: "å legge hodet i bløt", has: true, level: "C1",
    explanation: "Кад дуго размишљаш о проблему. Норвешки: „ставити главу да се размекша у води“." },
  { dir: "sr", re: /nema\w? pojma/, original: "немам појма", literal: "jeg har ikke begrep", equivalent: "jeg aner ikke / ingen anelse", has: true, level: "A2",
    explanation: "Најчешће „Jeg aner ikke“ или кратко „Aner ikke“." },
  { dir: "sr", re: /\bbez veze\b/, original: "без везе", literal: "uten forbindelse", equivalent: "så teit! / det gir ingen mening", has: false, level: "B1",
    explanation: "Нема истог израза. За нешто глупо: „så teit!“, за нешто бесмислено: „det gir ingen mening“." },
  { dir: "sr", re: /kao iz kabla/, original: "пада киша као из кабла", literal: "det regner som fra en bøtte", equivalent: "det regner trollkjerringer / det øser ned", has: true, level: "B2",
    explanation: "„Trollkjerringer“ су вештице: киша пада као да падају вештице. Свакодневније: „det øser ned“." },
  { dir: "sr", re: /macji kasalj/, original: "мачји кашаљ", literal: "katteshoste", equivalent: "en smal sak / barnemat", has: true, level: "B2",
    explanation: "За нешто лако: „Det er en smal sak“ или „det er barnemat“ (дечја храна)." },
  { dir: "sr", re: /dve muve/, original: "убити две муве једним ударцем", literal: "å drepe to fluer med ett slag", equivalent: "å slå to fluer i én smekk", has: true, level: "B1",
    explanation: "Исти израз, скоро од речи до речи." },
  { dir: "sr", re: /rano rani/, original: "ко рано рани, две среће граби", literal: "den som står tidlig opp, griper to lykker", equivalent: "morgenstund har gull i munn", has: true, level: "B2",
    explanation: "Норвешка пословица: „јутро има злато у устима“." },
  { dir: "sr", re: /vrabac u ruci/, original: "боље врабац у руци него голуб на грани", literal: "bedre en spurv i hånden enn en due på grenen", equivalent: "bedre med én fugl i hånden enn ti på taket", has: true, level: "B2",
    explanation: "Иста мисао: „боље једна птица у руци него десет на крову“." },
  { dir: "sr", re: /(gura|zabada|tura)\w* nos u/, original: "гурати нос у туђе ствари", literal: "å dytte nesen i fremmede ting", equivalent: "å stikke nesen sin i andres saker", has: true, level: "B1",
    explanation: "Скоро исти израз." },
  { dir: "sr", re: /glavu u pesak/, original: "забити главу у песак", literal: "å stikke hodet i sanden", equivalent: "å stikke hodet i sanden", has: true, level: "B1",
    explanation: "Исти израз." },
  { dir: "sr", re: /leptiric/, original: "лептирићи у стомаку", literal: "små sommerfugler i magen", equivalent: "å ha sommerfugler i magen", has: true, level: "B1",
    explanation: "Исти израз: „Jeg har sommerfugler i magen.“" },
  { dir: "sr", re: /\bsve pet\b/, original: "све пет", literal: "alt fem", equivalent: "alt i orden / helt topp", has: false, level: "A2",
    explanation: "Израз долази од школске оцене 5. Норвешки нема исту слику: „alt er i orden“ или „helt topp!“." },
  { dir: "sr", re: /(pao|pala|pali) (s|sa) marsa/, original: "као да је пао с Марса", literal: "som om han falt fra Mars", equivalent: "å være helt på jordet", has: true, level: "C1",
    explanation: "За некога ко појма нема шта се дешава. „Han er helt på jordet“, дословно „потпуно је на њиви“." },
  { dir: "sr", re: /sedmom nebu/, original: "бити на седмом небу", literal: "å være på den sjuende himmelen", equivalent: "å være i den sjuende himmel", has: true, level: "B1",
    explanation: "Исти израз." },
  { dir: "sr", re: /prod\w* maglu/, original: "продавати маглу", literal: "å selge tåke", equivalent: "å love gull og grønne skoger / å lure folk", has: false, level: "C1",
    explanation: "Нема тачног еквивалента. Ако неко обећава немогуће: „å love gull og grønne skoger“, ако вара: „å lure folk“." },
  { dir: "sr", re: /ne lezi vraze/, original: "не лези враже", literal: "ikke legg deg, djevel", equivalent: "men så skjedde det likevel", has: false, level: "C1",
    explanation: "Нема норвешког израза. Најприродније: „men så skjedde det likevel“ (али онда се ипак десило)." },
  { dir: "sr", re: /od ruke/, original: "иде ми од руке", literal: "det går meg fra hånden", equivalent: "å ha teken på (noe)", has: true, level: "C1",
    explanation: "„Hun har teken på det“: има дар за то." },
  { dir: "sr", re: /baci\w* oko/, original: "бацити око", literal: "å kaste et øye", equivalent: "å ta en titt på / å kaste et blikk på", has: true, level: "B1",
    explanation: "Свакодневно: „Kan du ta en titt på dette?“" },
  { dir: "sr", re: /bubreg u loju/, original: "живети као бубрег у лоју", literal: "å leve som en nyre i talg", equivalent: "å leve som plommen i egget", has: true, level: "C1",
    explanation: "Норвешки: живети „као жуманце у јајету“." },
  { dir: "sr", re: /svaka cast/, original: "свака част", literal: "all ære", equivalent: "hatten av! / godt jobba!", has: true, level: "A2",
    explanation: "За похвалу: „Hatten av for deg!“ или свакодневно „Godt jobba!“." },
  { dir: "sr", re: /\bnema veze\b/, original: "нема везе", literal: "det er ingen forbindelse", equivalent: "det gjør ingenting / det går fint", has: true, level: "A2",
    explanation: "Кад нешто није важно: „Det gjør ingenting.“" },
  { dir: "sr", re: /hvala bogu/, original: "хвала Богу", literal: "takk Gud", equivalent: "takk og lov / heldigvis", has: true, level: "A2",
    explanation: "„Takk og lov!“ или краће „heldigvis“ (срећом)." },
  { dir: "sr", re: /od smeha/, original: "умрети (пући) од смеха", literal: "å dø av latter", equivalent: "å le seg i hjel", has: true, level: "B1",
    explanation: "„Jeg lo meg i hjel“: умро сам од смеха." },
  { dir: "sr", re: /kao po loju/, original: "ићи као по лоју", literal: "å gå som på talg", equivalent: "å gå som smurt", has: true, level: "B1",
    explanation: "„Det gikk som smurt“: ишло је као подмазано." },
  { dir: "sr", re: /u isti kos/, original: "трпати све у исти кош", literal: "å putte alt i samme kurv", equivalent: "å skjære alle over én kam", has: true, level: "C1",
    explanation: "Норвешки: „сећи све преко истог чешља“." },
  { dir: "sr", re: /prste u/, original: "имати прсте у нечему", literal: "å ha fingrene i noe", equivalent: "å ha en finger med i spillet", has: true, level: "C1",
    explanation: "Норвешки: „имати прст у игри“." },
  { dir: "sr", re: /kratkih rukava/, original: "остати кратких рукава", literal: "å bli igjen med korte ermer", equivalent: "å stå med skjegget i postkassen", has: true, level: "C1",
    explanation: "„Стајати са брадом у поштанском сандучету“: остати празних руку и посрамљен." },
  { dir: "sr", re: /nema frke/, original: "нема фрке", literal: "det er ingen panikk", equivalent: "ingen ko på isen", has: true, level: "B2",
    explanation: "„Нема краве на леду“: нема разлога за бригу." },
  { dir: "sr", re: /zagri\w* vise/, original: "загристи више него што може да прогута", literal: "å bite mer enn man kan svelge", equivalent: "å ta seg vann over hodet", has: true, level: "C1",
    explanation: "Норвешки: „узети себи воду преко главе“." },
  { dir: "sr", re: /\bni govora\b/, original: "ни говора", literal: "ikke tale om", equivalent: "ikke snakk om!", has: true, level: "B1",
    explanation: "Одлучно одбијање: „Ikke snakk om!“" },
  { dir: "sr", re: /\bizvoli\w*/, original: "изволи(те)", literal: "vær så god", equivalent: "værsågod", has: true, level: "A1",
    explanation: "„Værsågod“ кад нешто пружаш или нудиш, и као позив за сто." },

  // ---------------- норвешки → српски ----------------
  { dir: "no", re: /regner trollkjerringer/, original: "det regner trollkjerringer", literal: "пада киша вештица", equivalent: "пада киша као из кабла", has: true, level: "B2",
    explanation: "Врло јака киша." },
  { dir: "no", re: /\bflaks\b/, original: "å ha flaks", literal: "имати флакс", equivalent: "имати среће / пала ми је секира у мед", has: true, level: "A2",
    explanation: "„Flaks“ значи срећа (случајна). „For en flaks!“: каква срећа!" },
  { dir: "no", re: /min kopp te/, original: "det er ikke min kopp te", literal: "то није моја шоља чаја", equivalent: "није по мом укусу", has: true, level: "B1",
    explanation: "Преузето из енглеског; значи да ти се нешто не допада." },
  { dir: "no", re: /som smurt/, original: "å gå som smurt", literal: "ићи као подмазано", equivalent: "ићи као по лоју", has: true, level: "B1",
    explanation: "Кад све иде без проблема." },
  { dir: "no", re: /morgenstund/, original: "morgenstund har gull i munn", literal: "јутарњи час има злато у устима", equivalent: "ко рано рани, две среће граби", has: true, level: "B2",
    explanation: "Пословица о раном устајању." },
  { dir: "no", re: /to torsdager/, original: "når det blir to torsdager i en uke", literal: "кад буду два четвртка у недељи", equivalent: "кад на врби роди грожђе", has: true, level: "B2",
    explanation: "Никад." },
  { dir: "no", re: /to fluer/, original: "å slå to fluer i én smekk", literal: "ударити две муве једним пљеском", equivalent: "убити две муве једним ударцем", has: true, level: "B1",
    explanation: "Исти израз." },
  { dir: "no", re: /tommelen/, original: "å holde tommelen (for noen)", literal: "држати палац (за некога)", equivalent: "држати палчеве", has: true, level: "A2",
    explanation: "„Jeg holder tommelen for deg!“" },
  { dir: "no", re: /på jordet/, original: "å være helt på jordet", literal: "бити потпуно на њиви", equivalent: "немати појма / као да је пао с Марса", has: true, level: "C1",
    explanation: "Кад неко уопште не разуме шта се дешава." },
  { dir: "no", re: /skoen trykker/, original: "det er der skoen trykker", literal: "ту ципела жуља", equivalent: "ту је зец", has: true, level: "B2",
    explanation: "Ту је прави проблем." },
  { dir: "no", re: /ikke snakk om/, original: "ikke snakk om!", literal: "не причај о (томе)!", equivalent: "ни говора!", has: true, level: "B1",
    explanation: "Одлучно одбијање." },
  { dir: "no", re: /vann over hodet/, original: "å ta seg vann over hodet", literal: "узети себи воду преко главе", equivalent: "загристи више него што може да прогута", has: true, level: "C1",
    explanation: "Прихватити посао који је претежак." },
  { dir: "no", re: /over (én|en|ein) kam/, original: "å skjære alle over én kam", literal: "сећи све преко једног чешља", equivalent: "трпати све у исти кош", has: true, level: "C1",
    explanation: "Генерализовати, не правити разлику." },
  { dir: "no", re: /finger med i spillet/, original: "å ha en finger med i spillet", literal: "имати прст у игри", equivalent: "имати прсте у нечему", has: true, level: "C1",
    explanation: "Бити умешан у нешто." },
  { dir: "no", re: /fra levra/, original: "å snakke rett fra levra", literal: "причати право из јетре", equivalent: "без длаке на језику", has: true, level: "C1",
    explanation: "Рећи отворено шта мислиш." },
  { dir: "no", re: /skjegget i postkassen/, original: "å stå med skjegget i postkassen", literal: "стајати са брадом у поштанском сандучету", equivalent: "остати кратких рукава", has: true, level: "C1",
    explanation: "Остати празних руку, посрамљен." },
  { dir: "no", re: /ko på isen/, original: "ingen ko på isen", literal: "нема краве на леду", equivalent: "нема фрке", has: true, level: "B2",
    explanation: "Нема разлога за бригу." },
  { dir: "no", re: /smørøyet/, original: "å sitte midt i smørøyet", literal: "седети усред ока од маслаца", equivalent: "бити на најбољем месту", has: false, level: "C1",
    explanation: "„Smørøye“ је рупица растопљеног маслаца у каши, најбољи део. Значи бити на најбољем месту у право време." },
  { dir: "no", re: /\bkoselig\b|\bkos\b/, original: "koselig / kos", literal: "пријатно, удобно", equivalent: "пријатно, топло, ушушкано", has: false, level: "A2",
    explanation: "Једна од најважнијих норвешких речи: осећај топлине и уживања у друштву или код куће (свеће, ћебе, кафа). Нема једне српске речи." },
  { dir: "no", re: /dugnad/, original: "dugnad", literal: "дугнад", equivalent: "заједнички добровољни рад (радна акција)", has: false, level: "B1",
    explanation: "Норвешки обичај: комшије или родитељи заједно, без плате, уређују двориште, школу или клуб." },
  { dir: "no", re: /takk for sist/, original: "takk for sist", literal: "хвала за прошли пут", equivalent: "лепо што се опет видимо", has: false, level: "B1",
    explanation: "Поздрав кад сретнеш некога с ким си се последњи пут дружио: захваљујеш се за то дружење. У српском нема таквог поздрава." },
  { dir: "no", re: /takk for maten/, original: "takk for maten", literal: "хвала за храну", equivalent: "хвала на ручку (вечери)", has: false, level: "A1",
    explanation: "Каже се после сваког оброка, а домаћин одговара „vel bekomme“. У Србији се обично каже „пријатно“ пре јела." },
  { dir: "no", re: /pålegg/, original: "pålegg", literal: "оно што се ставља на", equivalent: "све што се ставља на хлеб (сир, шунка, паштета…)", has: false, level: "A2",
    explanation: "Једна реч за све што иде на хлеб. У српском нема збирне речи." },
  { dir: "no", re: /(sjuende|syvende) himmel/, original: "å være i den sjuende himmel", literal: "бити у седмом небу", equivalent: "бити на седмом небу", has: true, level: "B1",
    explanation: "Исти израз." },
  { dir: "no", re: /lyn fra klar himmel/, original: "som lyn fra klar himmel", literal: "као муња из ведрог неба", equivalent: "као гром из ведра неба", has: true, level: "B1",
    explanation: "Изненада, неочекивано." },
  { dir: "no", re: /på nervene/, original: "å gå noen på nervene", literal: "ићи некоме на живце", equivalent: "ићи некоме на живце", has: true, level: "A2",
    explanation: "Исти израз." },
  { dir: "no", re: /\borke[rt]?\b/, original: "orke", literal: "имати снаге (воље)", equivalent: "није ми до тога / немам снаге", has: false, level: "A2",
    explanation: "„Jeg orker ikke“: немам снаге или воље. Врло честа реч без тачне српске замене." },
  { dir: "no", re: /aner ikke/, original: "jeg aner ikke", literal: "ја не слутим", equivalent: "немам појма", has: true, level: "A2",
    explanation: "Најчешћи начин да се каже „не знам“." },
  { dir: "no", re: /hatten av/, original: "hatten av!", literal: "шешир доле!", equivalent: "свака част!", has: true, level: "B1",
    explanation: "Похвала, дивљење." },
  { dir: "no", re: /værsågod|vær så god/, original: "værsågod", literal: "буди тако добар", equivalent: "изволи(те)", has: true, level: "A1",
    explanation: "Кад нешто пружаш или нудиш, и као позив за сто." },
];
